import { SettingsCategoryMeta, SearchableSettingItem } from "./types";

export const SETTINGS_CATEGORIES: SettingsCategoryMeta[] = [
  // GENERAL
  {
    key: "overview",
    label: "Settings Overview",
    description: "Executive control panel, health status cards, admin alerts, and quick actions",
    group: "GENERAL",
    iconName: "LayoutDashboard",
    minRoleLevel: 10,
    keywords: ["overview", "dashboard", "summary", "status", "health", "admin", "alerts"],
  },
  {
    key: "account",
    label: "My Account",
    description: "Personal profile, preferences, password, active sessions, and data export",
    group: "GENERAL",
    iconName: "User",
    minRoleLevel: 10,
    keywords: ["profile", "name", "email", "phone", "photo", "password", "sessions", "timezone", "language", "theme"],
  },
  {
    key: "organization",
    label: "Organization & Company",
    description: "Corporate legal entity, tax registration, address, branding, and fiscal year",
    group: "GENERAL",
    iconName: "Building",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CFO"],
    keywords: ["company", "legal name", "logo", "branding", "tax", "fiscal year", "currency", "address", "website"],
  },
  {
    key: "appearance",
    label: "Appearance & Theme",
    description: "Light mode, dark mode, compact density, dashboard styling, and branding colors",
    group: "GENERAL",
    iconName: "Palette",
    minRoleLevel: 10,
    keywords: ["theme", "dark mode", "light mode", "system", "density", "styling", "colors", "ui"],
  },
  {
    key: "localization",
    label: "Localization & Time",
    description: "Default language, base currency, regional timezone, and date/time formats",
    group: "GENERAL",
    iconName: "Globe",
    minRoleLevel: 50,
    keywords: ["language", "currency", "timezone", "date format", "time format", "number format", "calendar"],
  },

  // SECURITY & ACCESS
  {
    key: "users",
    label: "Users & Employees",
    description: "User directory, invitations, access status, department assignments, and session controls",
    group: "SECURITY",
    iconName: "Users",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "DEPARTMENT_HEAD"],
    keywords: ["users", "employees", "invite", "activate", "suspend", "reset password", "roles", "department"],
  },
  {
    key: "roles",
    label: "Roles & Permissions",
    description: "Granular Role-Based Access Control (RBAC), custom roles, and permission matrix",
    group: "SECURITY",
    iconName: "ShieldCheck",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON"],
    keywords: ["roles", "permissions", "rbac", "matrix", "access", "privileges", "executive", "employee"],
  },
  {
    key: "security",
    label: "Security Center",
    description: "Security score, active device sessions, password policies, and lockout thresholds",
    group: "SECURITY",
    iconName: "Shield",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CTO"],
    keywords: ["security", "password policy", "timeout", "lockout", "sessions", "login attempts", "ip restrictions"],
  },
  {
    key: "authentication",
    label: "Authentication & 2FA",
    description: "Multi-factor authentication (2FA), Google SSO, Passkeys/WebAuthn, and login methods",
    group: "SECURITY",
    iconName: "KeyRound",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CTO"],
    keywords: ["auth", "2fa", "sso", "google", "passkeys", "webauthn", "mfa", "backup codes", "session duration"],
  },

  // OPERATIONS
  {
    key: "crm",
    label: "CRM & Clients",
    description: "Lead statuses, qualification scoring, client categories, duplicate detection, and numbering",
    group: "OPERATIONS",
    iconName: "Briefcase",
    minRoleLevel: 50,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CMO"],
    keywords: ["crm", "leads", "clients", "scoring", "sources", "duplicate detection", "categories", "numbering"],
  },
  {
    key: "sales",
    label: "Sales & Pipelines",
    description: "Pipeline stages, win probabilities, deal statuses, sales quotas, and conversion rules",
    group: "OPERATIONS",
    iconName: "TrendingUp",
    minRoleLevel: 50,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CMO"],
    keywords: ["sales", "pipeline", "deals", "stages", "probability", "targets", "quota", "conversion"],
  },
  {
    key: "tasks",
    label: "Tasks & Projects",
    description: "Task priorities, statuses, project templates, milestone defaults, and calendar rules",
    group: "OPERATIONS",
    iconName: "CheckSquare",
    minRoleLevel: 30,
    keywords: ["tasks", "projects", "milestones", "priorities", "calendar", "due dates", "working hours"],
  },
  {
    key: "finance",
    label: "Finance & Invoicing",
    description: "Invoice numbering prefix, payment terms, tax configuration, late fees, and expense limits",
    group: "OPERATIONS",
    iconName: "DollarSign",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CFO"],
    keywords: ["finance", "invoices", "prefix", "tax", "payment terms", "late fee", "expenses", "approvals"],
  },
  {
    key: "inventory",
    label: "Products & Inventory",
    description: "Low-stock alerts, critical thresholds, valuation method (FIFO), warehouses, and categories",
    group: "OPERATIONS",
    iconName: "Package",
    minRoleLevel: 50,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CFO", "CTO"],
    keywords: ["inventory", "products", "warehouses", "low stock", "threshold", "valuation", "reorder", "fifo"],
  },
  {
    key: "vendors",
    label: "Vendors & Procurement",
    description: "Vendor categories, purchase order numbering prefix, PO approval limits, and workflows",
    group: "OPERATIONS",
    iconName: "Truck",
    minRoleLevel: 50,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CFO"],
    keywords: ["vendors", "procurement", "purchase orders", "po prefix", "approval limits", "payment terms"],
  },
  {
    key: "contracts",
    label: "Contracts & Compliance",
    description: "Contract types, renewal reminders, statutory compliance categories, and escalation intervals",
    group: "OPERATIONS",
    iconName: "Scale",
    minRoleLevel: 50,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON"],
    keywords: ["contracts", "legal", "compliance", "renewals", "reminders", "expiry", "escalation"],
  },
  {
    key: "hr",
    label: "HR & Payroll",
    description: "Working days, business hours, leave policies, salary components, pay cycles, and payroll rules",
    group: "OPERATIONS",
    iconName: "Users2",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CFO", "DEPARTMENT_HEAD"],
    keywords: ["hr", "payroll", "leave", "attendance", "working days", "salary", "pay cycle", "departments"],
  },

  // AUTOMATION
  {
    key: "workflows",
    label: "Workflow Automation",
    description: "Event-driven triggers, escalation ladders, automated task generation, and action rules",
    group: "AUTOMATION",
    iconName: "Zap",
    minRoleLevel: 50,
    keywords: ["workflows", "automation", "triggers", "actions", "escalations", "rules", "smart actions"],
  },
  {
    key: "ai",
    label: "AI Intelligence & LLMs",
    description: "Neural LLM provider, models, daily token limits, AI auto-actions, and role boundaries",
    group: "AUTOMATION",
    iconName: "Sparkles",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CTO"],
    keywords: ["ai", "openai", "models", "tokens", "llm", "smart actions", "advisor", "intelligence"],
  },
  {
    key: "notifications",
    label: "Notifications & Channels",
    description: "In-app alerts, email dispatch, push notifications, quiet hours, and category preferences",
    group: "AUTOMATION",
    iconName: "Bell",
    minRoleLevel: 10,
    keywords: ["notifications", "email alerts", "push", "in-app", "quiet hours", "preferences", "channels"],
  },
  {
    key: "communication",
    label: "Communication & Chat",
    description: "Channel creation permissions, group chat retention, broadcast announcements, and file limits",
    group: "AUTOMATION",
    iconName: "MessageSquare",
    minRoleLevel: 50,
    keywords: ["chat", "communication", "channels", "announcements", "retention", "attachments", "messages"],
  },

  // DEVELOPER & INFRASTRUCTURE
  {
    key: "integrations",
    label: "Connected Apps & OAuth",
    description: "Third-party integrations (Slack, GitHub, Stripe, Google Workspace), sync logs, and health",
    group: "DEVELOPER",
    iconName: "Plug",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CTO"],
    keywords: ["integrations", "slack", "github", "stripe", "google", "oauth", "sync", "connected apps"],
  },
  {
    key: "developer",
    label: "API Keys & Webhooks",
    description: "REST API keys management, webhook endpoints, event subscriptions, and rate limits",
    group: "DEVELOPER",
    iconName: "Code2",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CTO"],
    keywords: ["api", "api keys", "webhooks", "developer", "endpoints", "rate limits", "documentation"],
  },
  {
    key: "mobile",
    label: "Mobile & PWA",
    description: "Progressive Web App (PWA) configuration, offline caching, push tokens, and mobile sessions",
    group: "DEVELOPER",
    iconName: "Smartphone",
    minRoleLevel: 50,
    keywords: ["mobile", "pwa", "offline", "push", "sessions", "app name", "caching"],
  },
  {
    key: "storage",
    label: "Files & Storage",
    description: "Object storage engine, maximum upload file size, allowed extensions, and retention",
    group: "DEVELOPER",
    iconName: "HardDrive",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CTO"],
    keywords: ["storage", "s3", "files", "uploads", "extensions", "file size", "retention"],
  },
  {
    key: "email",
    label: "Email & Outbound Mail",
    description: "Outbound SMTP/SES provider, sender address, notification templates, and test mailer",
    group: "DEVELOPER",
    iconName: "Mail",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CTO"],
    keywords: ["email", "smtp", "ses", "sender", "templates", "test email", "mail provider"],
  },

  // SYSTEM & GOVERNANCE
  {
    key: "reports",
    label: "Reports & Analytics",
    description: "Executive report permissions, scheduled reports, export formats (CSV/PDF), and retention",
    group: "SYSTEM",
    iconName: "BarChart3",
    minRoleLevel: 50,
    keywords: ["reports", "analytics", "scheduled", "exports", "pdf", "csv", "excel", "retention"],
  },
  {
    key: "data",
    label: "Data Import & Export",
    description: "Bulk data import (clients, leads, products, vendors) and complete organization data export",
    group: "SYSTEM",
    iconName: "Database",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CFO"],
    keywords: ["data", "import", "export", "backup", "csv", "json", "maintenance", "cleanup"],
  },
  {
    key: "audit",
    label: "Audit Trail & Activity",
    description: "Enterprise audit logging stream, actor attribution, mutation tracking, and compliance logs",
    group: "SYSTEM",
    iconName: "ShieldAlert",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON"],
    keywords: ["audit", "logs", "activity", "security events", "mutations", "history", "compliance"],
  },
  {
    key: "billing",
    label: "Billing & Subscription",
    description: "Enterprise license tier, seat usage, billing cycle, corporate invoices, and plan limits",
    group: "SYSTEM",
    iconName: "CreditCard",
    minRoleLevel: 80,
    allowedRoles: ["SUPER_ADMIN", "ADMIN", "CEO", "CHAIRPERSON", "CFO"],
    keywords: ["billing", "subscription", "plan", "seats", "license", "invoices", "payment method"],
  },
  {
    key: "health",
    label: "System Health Telemetry",
    description: "Live health checks for database, API response times, storage, background workers, and AI",
    group: "SYSTEM",
    iconName: "Activity",
    minRoleLevel: 50,
    keywords: ["health", "status", "uptime", "latency", "services", "database", "telemetry", "checks"],
  },
  {
    key: "danger",
    label: "Danger Zone",
    description: "Organization configuration reset, audit log purge, and destructive administrative actions",
    group: "SYSTEM",
    iconName: "AlertTriangle",
    minRoleLevel: 100,
    allowedRoles: ["SUPER_ADMIN"],
    keywords: ["danger", "reset", "purge", "delete", "destructive", "organization reset", "factory defaults"],
  },
];

export const SEARCHABLE_SETTINGS: SearchableSettingItem[] = [
  { id: "s1", key: "auth.require_2fa", label: "Two-Factor Authentication (2FA)", category: "authentication", categoryLabel: "Authentication & 2FA", description: "Mandate multi-factor authentication for all enterprise users", keywords: ["2fa", "mfa", "security", "two factor", "otp", "auth"] },
  { id: "s2", key: "org.default_currency", label: "Default Currency", category: "organization", categoryLabel: "Organization & Company", description: "Primary currency code used for invoices, deals, and reports", keywords: ["currency", "usd", "money", "accounting", "finance"] },
  { id: "s3", key: "account.timezone", label: "Timezone", category: "localization", categoryLabel: "Localization & Time", description: "Regional timezone for scheduling, attendance, and timestamps", keywords: ["timezone", "time", "clock", "region", "gmt", "utc"] },
  { id: "s4", key: "security.password_min_length", label: "Password Policy", category: "security", categoryLabel: "Security Center", description: "Minimum length and character complexity rules for passwords", keywords: ["password", "length", "security", "complexity", "policy"] },
  { id: "s5", key: "security.session_timeout_minutes", label: "Session Inactivity Timeout", category: "security", categoryLabel: "Security Center", description: "Automatic sign-out duration following inactivity", keywords: ["timeout", "session", "inactivity", "sign out", "idle"] },
  { id: "s6", key: "finance.invoice_prefix", label: "Invoice Numbering Prefix", category: "finance", categoryLabel: "Finance & Invoicing", description: "Sequential serial prefix for all newly created customer invoices", keywords: ["invoice", "prefix", "numbering", "serial", "billing"] },
  { id: "s7", key: "finance.default_tax_rate", label: "Standard Tax / GST Rate (%)", category: "finance", categoryLabel: "Finance & Invoicing", description: "Default tax percentage applied on commercial invoice lines", keywords: ["tax", "gst", "vat", "rate", "percentage", "finance"] },
  { id: "s8", key: "inventory.low_stock_threshold", label: "Low Stock Alert Threshold", category: "inventory", categoryLabel: "Products & Inventory", description: "Stock quantity level that triggers replenishment alerts", keywords: ["inventory", "stock", "threshold", "reorder", "warehouse"] },
  { id: "s9", key: "ai.enabled", label: "AI Intelligence Master Switch", category: "ai", categoryLabel: "AI Intelligence & LLMs", description: "Enable or disable neural AI capabilities organization-wide", keywords: ["ai", "llm", "smart actions", "intelligence", "gpt"] },
  { id: "s10", key: "dev.api_rate_limit_rpm", label: "API Rate Limiting", category: "developer", categoryLabel: "API Keys & Webhooks", description: "Maximum requests per minute allowed per developer API key", keywords: ["api", "rate limit", "developer", "webhooks", "rpm"] },
  { id: "s11", key: "email.sender_email", label: "Outbound Email Address", category: "email", categoryLabel: "Email & Outbound Mail", description: "From email address used for all transactional notifications", keywords: ["email", "smtp", "sender", "mail", "notification"] },
  { id: "s12", key: "hr.work_days", label: "Standard Business Work Days", category: "hr", categoryLabel: "HR & Payroll", description: "Configured operating days for attendance, leave, and payroll", keywords: ["work days", "schedule", "calendar", "hr", "attendance", "weekend"] },
  { id: "s13", key: "crm.duplicate_detection", label: "CRM Duplicate Detection", category: "crm", categoryLabel: "CRM & Clients", description: "Automatic duplicate matching rules for incoming leads and clients", keywords: ["crm", "duplicate", "leads", "clients", "matching"] },
  { id: "s14", key: "appearance.theme", label: "Theme (Dark / Light / System)", category: "appearance", categoryLabel: "Appearance & Theme", description: "Visual appearance mode across all platform workspaces", keywords: ["theme", "dark", "light", "appearance", "mode", "color"] },
  { id: "s15", key: "notifications.quiet_hours_enabled", label: "Quiet Hours", category: "notifications", categoryLabel: "Notifications & Channels", description: "Suppress non-critical notifications during designated quiet hours", keywords: ["quiet hours", "notifications", "do not disturb", "dnd", "mute"] },
  { id: "s16", key: "comm.allow_announcements", label: "Broadcast Announcements Permissions", category: "communication", categoryLabel: "Communication & Chat", description: "Role authorization required to publish organization-wide notices", keywords: ["announcements", "broadcast", "chat", "communication", "permissions"] },
  { id: "s17", key: "storage.max_upload_size_mb", label: "Maximum File Upload Size", category: "storage", categoryLabel: "Files & Storage", description: "Ceiling limit for document and file attachments across the system", keywords: ["file size", "upload", "storage", "attachments", "mb"] },
  { id: "s18", key: "sales.default_pipeline", label: "Sales Pipeline Stages", category: "sales", categoryLabel: "Sales & Pipelines", description: "Configure sales stages, deal probabilities, and conversion quotas", keywords: ["sales", "pipeline", "deals", "stages", "probabilities"] },
  { id: "s19", key: "data.export", label: "Organization Data Export", category: "data", categoryLabel: "Data Management", description: "Download entire organization database records in JSON or CSV format", keywords: ["export", "data", "backup", "download", "json", "csv"] },
  { id: "s20", key: "danger.reset", label: "Reset System Configuration", category: "danger", categoryLabel: "Danger Zone", description: "Restore all parameters to verified enterprise factory defaults", keywords: ["danger", "reset", "factory defaults", "purge", "destructive"] },
];
