// Zoho Books sample inventory items matching the user's active CRM dataset
export const initialZohoItems = [
  {
    id: "MRSC",
    sku: "MRSC",
    name: "Monthly Recharge for Sim Card",
    type: "Service",
    itemTypeString: "Sales and Purchase Items (Service)",
    brand: "Telecommunications",
    manufacturer: "Telecom Provider",
    hsnCode: "997319",
    taxPreference: "Taxable",
    unit: "units",
    sellingPrice: "₹400.00",
    costPrice: "₹0.00",
    purchasePrice: "₹0.00",
    salesAccount: "Sales",
    purchaseAccount: "Cost of Goods Sold",
    salesDescription: "Monthly telecom recurring enterprise SIM card voice and data recharge.",
    purchaseDescription: "Direct cellular service voucher replenishment.",
    preferredVendor: "Telecom Operator Ltd",
    intraStateTax: "GST 18% [9% CGST + 9% SGST]",
    interStateTax: "IGST 18%",
    trackInventory: false,
    stock: "Non-tracked",
    status: "ACTIVE",
    isService: true,
    createdSource: "User",
  },
  {
    id: "VMF",
    sku: "VMF",
    name: "Variable Maintenance Facilities",
    type: "Service",
    itemTypeString: "Sales and Purchase Items (Service)",
    brand: "Facilities Mgmt",
    manufacturer: "Internal Service",
    hsnCode: "9954",
    taxPreference: "Taxable",
    unit: "units",
    sellingPrice: "₹0.00",
    costPrice: "₹0.00",
    purchasePrice: "₹0.00",
    salesAccount: "Sales",
    purchaseAccount: "Cost of Goods Sold",
    salesDescription: "On-demand facility upkeep, electrical audit, and preventive repairs.",
    purchaseDescription: "Subcontractor labor and consumable tools.",
    preferredVendor: "Facility Engineering Partners",
    intraStateTax: "GST 18% [9% CGST + 9% SGST]",
    interStateTax: "IGST 18%",
    trackInventory: false,
    stock: "Non-tracked",
    status: "ACTIVE",
    isService: true,
    createdSource: "User",
  },
  {
    id: "KDFS",
    sku: "KDFS",
    name: "Kachra Depot Flies Spraying",
    type: "Service",
    itemTypeString: "Sales and Purchase Items (Service)",
    brand: "Pest Management",
    manufacturer: "Naree Hygiene Div",
    hsnCode: "9985",
    taxPreference: "Taxable",
    unit: "units",
    sellingPrice: "₹1.00",
    costPrice: "₹0.50",
    purchasePrice: "₹0.50",
    salesAccount: "Sales",
    purchaseAccount: "Cost of Goods Sold",
    salesDescription: "Scheduled chemical barrier spraying for municipal garbage depot containment.",
    purchaseDescription: "Insecticide chemical supplies.",
    preferredVendor: "AgroChemical Supplies India",
    intraStateTax: "GST 18% [9% CGST + 9% SGST]",
    interStateTax: "IGST 18%",
    trackInventory: false,
    stock: "Non-tracked",
    status: "ACTIVE",
    isService: true,
    createdSource: "User",
  },
  {
    id: "MTS",
    sku: "MTS",
    name: "Mosquito Treatment - Spraying",
    type: "Service",
    itemTypeString: "Sales and Purchase Items (Service)",
    brand: "Pest Management",
    manufacturer: "Naree Hygiene Div",
    hsnCode: "9985",
    taxPreference: "Taxable",
    unit: "units",
    sellingPrice: "₹1.00",
    costPrice: "₹0.50",
    purchasePrice: "₹0.50",
    salesAccount: "Sales",
    purchaseAccount: "Cost of Goods Sold",
    salesDescription: "Larvicide residual surface spraying for vector borne mosquito control.",
    purchaseDescription: "Pesticide procurement.",
    preferredVendor: "AgroChemical Supplies India",
    intraStateTax: "GST 18% [9% CGST + 9% SGST]",
    interStateTax: "IGST 18%",
    trackInventory: false,
    stock: "Non-tracked",
    status: "ACTIVE",
    isService: true,
    createdSource: "User",
  },
  {
    id: "MFT",
    sku: "MFT",
    name: "Mosquito Fogging Treatment",
    type: "Service",
    itemTypeString: "Sales and Purchase Items (Service)",
    brand: "Pest Management",
    manufacturer: "Naree Hygiene Div",
    hsnCode: "9985",
    taxPreference: "Taxable",
    unit: "units",
    sellingPrice: "₹1.00",
    costPrice: "₹0.50",
    purchasePrice: "₹0.50",
    salesAccount: "Sales",
    purchaseAccount: "Cost of Goods Sold",
    salesDescription: "Thermal fogging treatment for commercial open spaces and parking lots.",
    purchaseDescription: "Diesel thermal fogging mixture.",
    preferredVendor: "AgroChemical Supplies India",
    intraStateTax: "GST 18% [9% CGST + 9% SGST]",
    interStateTax: "IGST 18%",
    trackInventory: false,
    stock: "Non-tracked",
    status: "ACTIVE",
    isService: true,
    createdSource: "User",
  },
  {
    id: "WDS",
    sku: "WDS",
    name: "Water Dispenser Servicing",
    type: "Service",
    itemTypeString: "Sales and Purchase Items (Service)",
    brand: "Appliance Care",
    manufacturer: "Aqua Pure Tech",
    hsnCode: "9987",
    taxPreference: "Taxable",
    unit: "units",
    sellingPrice: "₹1.00",
    costPrice: "₹0.00",
    purchasePrice: "₹0.00",
    salesAccount: "Sales",
    purchaseAccount: "Cost of Goods Sold",
    salesDescription: "Filter sanitization, descaling, and cooling coil inspection.",
    purchaseDescription: "Service kit filters and gaskets.",
    preferredVendor: "Aqua Service Direct",
    intraStateTax: "GST 18% [9% CGST + 9% SGST]",
    interStateTax: "IGST 18%",
    trackInventory: false,
    stock: "Non-tracked",
    status: "ACTIVE",
    isService: true,
    createdSource: "User",
  },
  {
    id: "SC-01",
    sku: "SC-01",
    name: "Service Charges",
    type: "Service",
    itemTypeString: "Sales and Purchase Items (Service)",
    brand: "Professional Services",
    manufacturer: "NFVS Consulting",
    hsnCode: "9983",
    taxPreference: "Taxable",
    unit: "units",
    sellingPrice: "₹1,250.00",
    costPrice: "₹500.00",
    purchasePrice: "₹500.00",
    salesAccount: "Sales",
    purchaseAccount: "Cost of Goods Sold",
    salesDescription: "Administrative and operational technical service fees.",
    purchaseDescription: "External specialist chargeback.",
    preferredVendor: "Professional Advisory Hub",
    intraStateTax: "GST 18% [9% CGST + 9% SGST]",
    interStateTax: "IGST 18%",
    trackInventory: false,
    stock: "Non-tracked",
    status: "ACTIVE",
    isService: true,
    createdSource: "User",
  },
  {
    id: "OT-01",
    sku: "OT-01",
    name: "Outsourcing Services",
    type: "Service",
    itemTypeString: "Sales and Purchase Items (Service)",
    brand: "BPO / Staffing",
    manufacturer: "NFVS Operations",
    hsnCode: "9983",
    taxPreference: "Taxable",
    unit: "units",
    sellingPrice: "₹8,712.00",
    costPrice: "₹6,000.00",
    purchasePrice: "₹6,000.00",
    salesAccount: "Sales",
    purchaseAccount: "Cost of Goods Sold",
    salesDescription: "Dedicated managed staffing and back-office outsourcing contract.",
    purchaseDescription: "Payroll contractor disbursements.",
    preferredVendor: "Staffing Solutions India",
    intraStateTax: "GST 18% [9% CGST + 9% SGST]",
    interStateTax: "IGST 18%",
    trackInventory: false,
    stock: "Non-tracked",
    status: "ACTIVE",
    isService: true,
    createdSource: "User",
  },
  {
    id: "RCT-01",
    sku: "RCT-01",
    name: "Rodent Control Treatment",
    type: "Service",
    itemTypeString: "Sales and Purchase Items (Service)",
    brand: "Pest Management",
    manufacturer: "Naree Hygiene Div",
    hsnCode: "9985",
    taxPreference: "Taxable",
    unit: "units",
    sellingPrice: "₹340.00",
    costPrice: "₹120.00",
    purchasePrice: "₹120.00",
    salesAccount: "Sales",
    purchaseAccount: "Cost of Goods Sold",
    salesDescription: "Tamper-resistant bait stations placement and glue board monitoring.",
    purchaseDescription: "Bait chemical blocks and station boxes.",
    preferredVendor: "AgroChemical Supplies India",
    intraStateTax: "GST 18% [9% CGST + 9% SGST]",
    interStateTax: "IGST 18%",
    trackInventory: false,
    stock: "Non-tracked",
    status: "ACTIVE",
    isService: true,
    createdSource: "User",
  },
  {
    id: "SKU-SVR-01",
    sku: "SKU-SVR-01",
    name: "Dell PowerEdge Rack Server",
    type: "Goods",
    itemTypeString: "Sales and Purchase Items (Goods)",
    brand: "Dell Technologies",
    manufacturer: "Dell India Pvt Ltd",
    hsnCode: "84715000",
    taxPreference: "Taxable",
    unit: "units",
    sellingPrice: "₹1,45,000.00",
    costPrice: "₹1,20,000.00",
    purchasePrice: "₹1,20,000.00",
    salesAccount: "Sales",
    purchaseAccount: "Cost of Goods Sold",
    salesDescription: "Enterprise PowerEdge 2U rack mountable server with dual Xeon CPUs and redundant PSU.",
    purchaseDescription: "OEM procurement for server hardware infrastructure.",
    preferredVendor: "TechDistributors India Pvt Ltd",
    intraStateTax: "GST 18% [9% CGST + 9% SGST]",
    interStateTax: "IGST 18%",
    trackInventory: true,
    stock: "12 Units",
    status: "ACTIVE",
    isService: false,
    createdSource: "User",
  },
  {
    id: "SKU-NET-24",
    sku: "SKU-NET-24",
    name: "Cisco 24-Port Gigabit Managed Switch",
    type: "Goods",
    itemTypeString: "Sales and Purchase Items (Goods)",
    brand: "Cisco Systems",
    manufacturer: "Cisco Solutions Corp",
    hsnCode: "85176290",
    taxPreference: "Taxable",
    unit: "units",
    sellingPrice: "₹36,500.00",
    costPrice: "₹28,000.00",
    purchasePrice: "₹28,000.00",
    salesAccount: "Sales",
    purchaseAccount: "Cost of Goods Sold",
    salesDescription: "Enterprise L2/L3 managed network switch with 24 Gigabit Ethernet PoE+ ports.",
    purchaseDescription: "Distributor purchase tier 1.",
    preferredVendor: "Ingram Micro India",
    intraStateTax: "GST 18% [9% CGST + 9% SGST]",
    interStateTax: "IGST 18%",
    trackInventory: true,
    stock: "35 Units",
    status: "ACTIVE",
    isService: false,
    createdSource: "User",
  },
];
